export const CARRIER = [
  {
    carrier_id: 1,
    value: 'fedex',
    title: 'FedEx',
    services: ['express', 'express_freight', 'ground'],
    country_code: 'MX',
    import: 0,
  },
  {
    carrier_id: 11,
    value: 'estafeta',
    title: 'Estafeta',
    services: ['express', 'ground', 'local', 'express_od', 'ground_od'],
    country_code: 'MX',
  },
  {
    carrier_id: 9,
    value: 'ups',
    title: 'UPS',
    services: ['saver'],
    country_code: 'MX',
  },
]

export const STATES = [
  {
    title: 'Aguascalientes',
    value: 'AG',
    code_3_digits: 'AGS',
    code_shopify: 'AGS',
    country_code: 'MX',
  },
  {
    title: 'Baja California',
    value: 'BC',
    code_3_digits: 'BCN',
    code_shopify: 'BC',
    country_code: 'MX',
  },
  {
    title: 'Baja California Sur',
    value: 'BS',
    code_3_digits: 'BCS',
    code_shopify: 'BCS',
    country_code: 'MX',
  },
  {
    title: 'Campeche',
    value: 'CM',
    code_3_digits: 'CAM',
    code_shopify: 'CAMP',
    country_code: 'MX',
  },
  {
    title: 'Chiapas',
    value: 'CS',
    code_3_digits: 'CHP',
    code_shopify: 'CHIS',
    country_code: 'MX',
  },
  {
    title: 'Chihuahua',
    value: 'CH',
    code_3_digits: 'CHH',
    code_shopify: 'CHIH',
    country_code: 'MX',
  },
  {
    title: 'Ciudad de México',
    value: 'CX',
    code_3_digits: 'CMX',
    code_shopify: 'DF',
    country_code: 'MX',
  },
  {
    title: 'Coahuila',
    value: 'CO',
    code_3_digits: 'COA',
    code_shopify: 'COAH',
    country_code: 'MX',
  },
  {
    title: 'Colima',
    value: 'CL',
    code_3_digits: 'COL',
    code_shopify: 'COL',
    country_code: 'MX',
  },
  {
    title: 'Durango',
    value: 'DG',
    code_3_digits: 'DGO',
    code_shopify: 'DGO',
    country_code: 'MX',
  },
  {
    title: 'Guanajuato',
    value: 'GT',
    code_3_digits: 'GTO',
    code_shopify: 'GTO',
    country_code: 'MX',
  },
  {
    title: 'Guerrero',
    value: 'GR',
    code_3_digits: 'GRO',
    code_shopify: 'GRO',
    country_code: 'MX',
  },
  {
    title: 'Hidalgo',
    value: 'HG',
    code_3_digits: 'HGO',
    code_shopify: 'HGO',
    country_code: 'MX',
  },
  {
    title: 'Jalisco',
    value: 'JA',
    code_3_digits: 'JAL',
    code_shopify: 'JAL',
    country_code: 'MX',
  },
  {
    title: 'México',
    value: 'EM',
    code_3_digits: 'MEX',
    code_shopify: 'MEX',
    country_code: 'MX',
  },
  {
    title: 'Michoacán',
    value: 'MI',
    code_3_digits: 'MIC',
    code_shopify: 'MICH',
    country_code: 'MX',
  },
  {
    title: 'Morelos',
    value: 'MO',
    code_3_digits: 'MOR',
    code_shopify: 'MOR',
    country_code: 'MX',
  },
  {
    title: 'Nayarit',
    value: 'NA',
    code_3_digits: 'NAY',
    code_shopify: 'NAY',
    country_code: 'MX',
  },
  {
    title: 'Nuevo León',
    value: 'NL',
    code_3_digits: 'NLE',
    code_shopify: 'NL',
    country_code: 'MX',
  },
  {
    title: 'Oaxaca',
    value: 'OA',
    code_3_digits: 'OAX',
    code_shopify: 'OAX',
    country_code: 'MX',
  },
  {
    title: 'Puebla',
    value: 'PU',
    code_3_digits: 'PUE',
    code_shopify: 'PUE',
    country_code: 'MX',
  },
  {
    title: 'Querétaro',
    value: 'QT',
    code_3_digits: 'QRO',
    code_shopify: 'QRO',
    country_code: 'MX',
  },
  {
    title: 'Quintana Roo',
    value: 'QR',
    code_3_digits: 'ROO',
    code_shopify: 'Q ROO',
    country_code: 'MX',
  },
  {
    title: 'San Luis Potosí',
    value: 'SL',
    code_3_digits: 'SLP',
    code_shopify: 'SLP',
    country_code: 'MX',
  },
  {
    title: 'Sinaloa',
    value: 'SI',
    code_3_digits: 'SIN',
    code_shopify: 'SIN',
    country_code: 'MX',
  },
  {
    title: 'Sonora',
    value: 'SO',
    code_3_digits: 'SON',
    code_shopify: 'SON',
    country_code: 'MX',
  },
  {
    title: 'Tabasco',
    value: 'TB',
    code_3_digits: 'TAB',
    code_shopify: 'TAB',
    country_code: 'MX',
  },
  {
    title: 'Tamaulipas',
    value: 'TM',
    code_3_digits: 'TAM',
    code_shopify: 'TAMPS',
    country_code: 'MX',
  },
  {
    title: 'Tlaxcala',
    value: 'TL',
    code_3_digits: 'TLA',
    code_shopify: 'TLAX',
    country_code: 'MX',
  },
  {
    title: 'Veracruz',
    value: 'VE',
    code_3_digits: 'VER',
    code_shopify: 'VER',
    country_code: 'MX',
  },
  {
    title: 'Yucatán',
    value: 'YU',
    code_3_digits: 'YUC',
    code_shopify: 'YUC',
    country_code: 'MX',
  },
  {
    title: 'Zacatecas',
    value: 'ZA',
    code_3_digits: 'ZAC',
    code_shopify: 'ZAC',
    country_code: 'MX',
  },
]

export const ESTAFETA = [
  {
    carrier: 'estafeta',
    carrierDescription: 'Estafeta',
    carrierId: 11,
    serviceId: 22,
    service: 'express',
    serviceDescription: 'Estafeta Express',
    dropOff: 0,
    branchType: null,
    zone: 3,
    deliveryEstimate: '1-3 días',
    deliveryDate: {
      date: '2025-08-10',
      dateDifference: 2,
      timeUnit: 'days',
      time: '20:00',
    },
    quantity: 1,
    basePrice: 159.48,
    basePriceTaxes: 25.52,
    extendedFare: 0,
    insurance: 0,
    additionalServices: 0,
    additionalServicesTaxes: 0,
    additionalCharges: 0,
    additionalChargesTaxes: 0,
    taxes: 25.52,
    totalPrice: 185,
    currency: 'MXN',
    customKey: false,
    importFee: 0,
    cashOnDeliveryCommission: 0,
    cashOnDeliveryAmount: 0,
    customKeyCost: 0,
    smsCost: 0,
    whatsappCost: 0,
    isMps: false,
    branches: [],
    costSummary: [
      {
        quantity: 1,
        basePrice: 159.48,
        basePriceTaxes: 25.52,
        extendedFare: 0,
        insurance: 0,
        additionalServices: 0,
        additionalServicesTaxes: 0,
        additionalCharges: 0,
        additionalChargesTaxes: 0,
        taxes: 25.52,
        totalPrice: 185,
        costAdditionalServices: [],
        costAdditionalCharges: [],
        currency: 'MXN',
        customKey: false,
        cashOnDeliveryCommission: 0,
        cashOnDeliveryAmount: 0,
        customKeyCommission: 0,
        smsCommission: 0,
        whatsappCommission: 0,
        securityDeposit: false,
        securityWeight: 1,
        importFee: 0,
        folio: null,
        calculatedDeclaredValue: 0,
        insertConcepts: [],
      },
    ],
    calculatedDeclaredValue: 0,
    packageDetails: {
      totalWeight: 1,
      weightUnit: 'KG',
      details: [
        {
          appliedWeightType: 'flatRate',
          weightUnit: 'KG',
          weight: 1,
          content: 'Caja .1KG - 10 x 10 x 10 cm',
        },
      ],
    },
  },
  {
    carrier: 'estafeta',
    carrierDescription: 'Estafeta',
    carrierId: 11,
    serviceId: 23,
    service: 'ground',
    serviceDescription: 'Estafeta Terrestre',
    dropOff: 0,
    branchType: null,
    zone: 3,
    deliveryEstimate: '2-5 días',
    deliveryDate: {
      date: '2025-08-13',
      dateDifference: 5,
      timeUnit: 'days',
      time: '20:00',
    },
    quantity: 1,
    basePrice: 155.17,
    basePriceTaxes: 24.83,
    extendedFare: 0,
    insurance: 0,
    additionalServices: 0,
    additionalServicesTaxes: 0,
    additionalCharges: 0,
    additionalChargesTaxes: 0,
    taxes: 24.83,
    totalPrice: 180,
    currency: 'MXN',
    customKey: false,
    importFee: 0,
    cashOnDeliveryCommission: 0,
    cashOnDeliveryAmount: 0,
    customKeyCost: 0,
    smsCost: 0,
    whatsappCost: 0,
    isMps: false,
    branches: [],
    costSummary: [
      {
        quantity: 1,
        basePrice: 155.17,
        basePriceTaxes: 24.83,
        extendedFare: 0,
        insurance: 0,
        additionalServices: 0,
        additionalServicesTaxes: 0,
        additionalCharges: 0,
        additionalChargesTaxes: 0,
        taxes: 24.83,
        totalPrice: 180,
        costAdditionalServices: [],
        costAdditionalCharges: [],
        currency: 'MXN',
        customKey: false,
        cashOnDeliveryCommission: 0,
        cashOnDeliveryAmount: 0,
        customKeyCommission: 0,
        smsCommission: 0,
        whatsappCommission: 0,
        securityDeposit: false,
        securityWeight: 1,
        importFee: 0,
        folio: null,
        calculatedDeclaredValue: 0,
        insertConcepts: [],
      },
    ],
    calculatedDeclaredValue: 0,
    packageDetails: {
      totalWeight: 1,
      weightUnit: 'KG',
      details: [
        {
          appliedWeightType: 'flatRate',
          weightUnit: 'KG',
          weight: 1,
          content: 'Caja .1KG - 10 x 10 x 10 cm',
        },
      ],
    },
  },
  {
    carrier: 'estafeta',
    carrierDescription: 'Estafeta',
    carrierId: 11,
    serviceId: 704,
    service: 'ground_od',
    serviceDescription: 'Estafeta Terrestre Ocurre - Domicilio',
    dropOff: 1,
    branchType: null,
    zone: 3,
    deliveryEstimate: '2-5 días',
    deliveryDate: {
      date: '2025-08-13',
      dateDifference: 5,
      timeUnit: 'days',
      time: '20:00',
    },
    quantity: 1,
    basePrice: 150.86,
    basePriceTaxes: 24.14,
    extendedFare: 0,
    insurance: 0,
    additionalServices: 0,
    additionalServicesTaxes: 0,
    additionalCharges: 0,
    additionalChargesTaxes: 0,
    taxes: 24.14,
    totalPrice: 175,
    currency: 'MXN',
    customKey: false,
    importFee: 0,
    cashOnDeliveryCommission: 0,
    cashOnDeliveryAmount: 0,
    customKeyCost: 0,
    smsCost: 0,
    whatsappCost: 0,
    isMps: false,
    branches: [
      {
        distance: 1.31,
        branch_id: '07C',
        branch_code: '07C',
        branch_type: 1,
        reference: 'Lagos de Moreno',
        address: {
          city: 'Lagos de Moreno',
          state: 'JA',
          number: '',
          street: 'Blvd Felix Ramirez #155',
          country: 'MX',
          delivery: true,
          latitude: '21.3618297',
          locality: 'Lagos de Moreno',
          admission: true,
          longitude: '-101.9201298',
          postalCode: '47430',
          address: 'Blvd Felix Ramirez #155 (Sucursal)',
          zipcode: '47430',
          province: 'JA',
        },
        hours: [],
      },
      {
        distance: 2.1,
        branch_id: '178',
        branch_code: '178',
        branch_type: 1,
        reference: 'Lagos de Moreno',
        address: {
          city: 'Lagos de Moreno',
          state: 'JA',
          number: '',
          street: 'Francisco I. Madero Pte. #864',
          country: 'MX',
          delivery: true,
          latitude: '21.353545',
          locality: 'Lagos de Moreno',
          admission: true,
          longitude: '-101.939865',
          postalCode: '47400',
          address: 'Francisco I. Madero Pte. #864 (Sucursal)',
          zipcode: '47400',
          province: 'JA',
        },
        hours: [],
      },
      {
        distance: 35.47,
        branch_id: '288',
        branch_code: '288',
        branch_type: 1,
        reference: 'León',
        address: {
          city: 'León',
          state: 'GT',
          number: '',
          street: 'Blvd. Adolfo López Mateos #429 Int 6',
          country: 'MX',
          delivery: true,
          latitude: '21.146095',
          locality: 'León',
          admission: true,
          longitude: '-101.685413',
          postalCode: '37160',
          address: 'Blvd. Adolfo López Mateos #429 Int 6 (Sucursal)',
          zipcode: '37160',
          province: 'GT',
        },
        hours: [],
      },
      {
        distance: 35.87,
        branch_id: '08C',
        branch_code: '08C',
        branch_type: 1,
        reference: 'Leon',
        address: {
          city: 'Leon',
          state: 'GT',
          number: '',
          street: 'Blvd Jose Ma Morelos #425 L-1Y2',
          country: 'MX',
          delivery: true,
          latitude: '21.1706878',
          locality: 'Leon',
          admission: true,
          longitude: '-101.65707',
          postalCode: '37207',
          address: 'Blvd Jose Ma Morelos #425 L-1Y2 (Sucursal)',
          zipcode: '37207',
          province: 'GT',
        },
        hours: [],
      },
      {
        distance: 37.85,
        branch_id: '139',
        branch_code: '139',
        branch_type: 1,
        reference: 'León',
        address: {
          city: 'León',
          state: 'GT',
          number: '',
          street: 'Donato Guerra #102',
          country: 'MX',
          delivery: true,
          latitude: '21.121314',
          locality: 'León',
          admission: true,
          longitude: '-101.679883',
          postalCode: '37000',
          address: 'Donato Guerra #102 (Sucursal)',
          zipcode: '37000',
          province: 'GT',
        },
        hours: [],
      },
      {
        distance: 38.45,
        branch_id: '381',
        branch_code: '381',
        branch_type: 1,
        reference: 'León',
        address: {
          city: 'León',
          state: 'GT',
          number: '',
          street: 'Prol. Juárez #1805 int 4',
          country: 'MX',
          delivery: true,
          latitude: '21.104114',
          locality: 'León',
          admission: true,
          longitude: '-101.692036',
          postalCode: '37390',
          address: 'Prol. Juárez #1805 int 4 (Sucursal)',
          zipcode: '37390',
          province: 'GT',
        },
        hours: [],
      },
      {
        distance: 38.5,
        branch_id: '389',
        branch_code: '389',
        branch_type: 1,
        reference: 'León',
        address: {
          city: 'León',
          state: 'GT',
          number: '',
          street: 'Monterrey #201 Int 3',
          country: 'MX',
          delivery: true,
          latitude: '21.12244',
          locality: 'León',
          admission: true,
          longitude: '-101.669559',
          postalCode: '37260',
          address: 'Monterrey #201 Int 3 (Sucursal)',
          zipcode: '37260',
          province: 'GT',
        },
        hours: [],
      },
      {
        distance: 38.74,
        branch_id: '219',
        branch_code: '219',
        branch_type: 1,
        reference: 'San Francisco del Rincón',
        address: {
          city: 'San Francisco del Rincón',
          state: 'GT',
          number: '',
          street: 'Hidalgo #711 L-17',
          country: 'MX',
          delivery: true,
          latitude: '21.027854',
          locality: 'San Francisco del Rincón',
          admission: true,
          longitude: '-101.858005',
          postalCode: '36300',
          address: 'Hidalgo #711 L-17 (Sucursal)',
          zipcode: '36300',
          province: 'GT',
        },
        hours: [],
      },
      {
        distance: 41.63,
        branch_id: '54C',
        branch_code: '54C',
        branch_type: 1,
        reference: 'Leon',
        address: {
          city: 'Leon',
          state: 'GT',
          number: '',
          street: 'Blvd. Hermanos Aldama #4003',
          country: 'MX',
          delivery: true,
          latitude: '21.075331',
          locality: 'Leon',
          admission: true,
          longitude: '-101.681484',
          postalCode: '37490',
          address: 'Blvd. Hermanos Aldama #4003 (Sucursal)',
          zipcode: '37490',
          province: 'GT',
        },
        hours: [],
      },
      {
        distance: 41.98,
        branch_id: '12A',
        branch_code: '12A',
        branch_type: 1,
        reference: 'León',
        address: {
          city: 'León',
          state: 'GT',
          number: '',
          street: 'Blvd. Torres Landa #4108 Int 4',
          country: 'MX',
          delivery: true,
          latitude: '21.096662',
          locality: 'León',
          admission: true,
          longitude: '-101.649796',
          postalCode: '37520',
          address: 'Blvd. Torres Landa #4108 Int 4 (Sucursal)',
          zipcode: '37520',
          province: 'GT',
        },
        hours: [],
      },
      {
        distance: 43.03,
        branch_id: '568',
        branch_code: '568',
        branch_type: 1,
        reference: 'León',
        address: {
          city: 'León',
          state: 'GT',
          number: '',
          street: 'Av. Curtidor #102 B',
          country: 'MX',
          delivery: true,
          latitude: '21.106187',
          locality: 'León',
          admission: true,
          longitude: '-101.625532',
          postalCode: '37290',
          address: 'Av. Curtidor #102 B (Sucursal)',
          zipcode: '37290',
          province: 'GT',
        },
        hours: [],
      },
      {
        distance: 43.28,
        branch_id: '329',
        branch_code: '329',
        branch_type: 1,
        reference: 'San Juan de Los Lagos',
        address: {
          city: 'San Juan de Los Lagos',
          state: 'JA',
          number: '',
          street: 'Blvd. Díaz Ordaz S/N L.8-1',
          country: 'MX',
          delivery: true,
          latitude: '21.2522258',
          locality: 'San Juan de Los Lagos',
          admission: true,
          longitude: '-102.3277066',
          postalCode: '47000',
          address: 'Blvd. Díaz Ordaz S/N L.8-1 (Sucursal)',
          zipcode: '47000',
          province: 'JA',
        },
        hours: [],
      },
    ],
    costSummary: [
      {
        quantity: 1,
        basePrice: 150.86,
        basePriceTaxes: 24.14,
        extendedFare: 0,
        insurance: 0,
        additionalServices: 0,
        additionalServicesTaxes: 0,
        additionalCharges: 0,
        additionalChargesTaxes: 0,
        taxes: 24.14,
        totalPrice: 175,
        costAdditionalServices: [],
        costAdditionalCharges: [],
        currency: 'MXN',
        customKey: false,
        cashOnDeliveryCommission: 0,
        cashOnDeliveryAmount: 0,
        customKeyCommission: 0,
        smsCommission: 0,
        whatsappCommission: 0,
        securityDeposit: false,
        securityWeight: 1,
        importFee: 0,
        folio: null,
        calculatedDeclaredValue: 0,
        insertConcepts: [],
      },
    ],
    calculatedDeclaredValue: 0,
    packageDetails: {
      totalWeight: 1,
      weightUnit: 'KG',
      details: [
        {
          appliedWeightType: 'flatRate',
          weightUnit: 'KG',
          weight: 1,
          content: 'Caja .1KG - 10 x 10 x 10 cm',
        },
      ],
    },
  },
]

export const FEDEX = [
  {
    carrierId: 1,
    carrier: 'fedex',
    carrierDescription: 'FedEx',
    serviceId: 1,
    service: 'ground',
    serviceDescription: 'FedEx Nacional Económico',
    dropOff: 0,
    branchType: null,
    zone: 5,
    deliveryEstimate: '2-4 días',
    deliveryDate: {
      date: '2025-08-12',
      dateDifference: 4,
      timeUnit: 'days',
      time: '21:00',
    },
    quantity: 1,
    basePrice: 161.21,
    basePriceTaxes: 25.79,
    extendedFare: 0,
    insurance: 0,
    additionalServices: 0,
    additionalServicesTaxes: 0,
    additionalCharges: 0,
    additionalChargesTaxes: 0,
    importFee: 0,
    customKeyCost: 0,
    taxes: 25.79,
    totalPrice: 187,
    currency: 'MXN',
    smsCost: 0,
    whatsappCost: 0,
    customKey: false,
    cashOnDeliveryCommission: 0,
    cashOnDeliveryAmount: 0,
    calculatedDeclaredValue: 0,
    isMps: false,
    shipmentTaxes: [],
    branches: [],
    costSummary: [
      {
        quantity: 1,
        basePrice: 161.21,
        basePriceTaxes: 25.79,
        extendedFare: 0,
        insurance: 0,
        additionalServices: 0,
        additionalServicesTaxes: 0,
        additionalCharges: 0,
        additionalChargesTaxes: 0,
        taxes: 25.79,
        totalPrice: 187,
        costAdditionalServices: [],
        costAdditionalCharges: [],
        currency: 'MXN',
        customKey: false,
        cashOnDeliveryCommission: 0,
        cashOnDeliveryAmount: 0,
        customKeyCommission: 0,
        smsCommission: 0,
        securityDeposit: false,
        securityWeight: 1,
        importFee: 0,
        whatsappCommission: 0,
        folio: null,
        calculatedDeclaredValue: 0,
      },
    ],
    packageDetails: {
      totalWeight: 1,
      weightUnit: 'KG',
      details: [
        {
          appliedWeightType: 'flatRate',
          weightUnit: 'KG',
          weight: 1,
          content: 'Caja .1KG - 10 x 10 x 10 cm',
        },
      ],
    },
  },
  {
    carrierId: 1,
    carrier: 'fedex',
    carrierDescription: 'FedEx',
    serviceId: 2,
    service: 'express',
    serviceDescription: 'FedEx Nacional Día Siguiente',
    dropOff: 0,
    branchType: null,
    zone: 5,
    deliveryEstimate: 'Día siguiente',
    deliveryDate: {
      date: '2025-08-11',
      dateDifference: 3,
      timeUnit: 'days',
      time: '21:00',
    },
    quantity: 1,
    basePrice: 169.83,
    basePriceTaxes: 27.17,
    extendedFare: 0,
    insurance: 0,
    additionalServices: 0,
    additionalServicesTaxes: 0,
    additionalCharges: 0,
    additionalChargesTaxes: 0,
    importFee: 0,
    customKeyCost: 0,
    taxes: 27.17,
    totalPrice: 197,
    currency: 'MXN',
    smsCost: 0,
    whatsappCost: 0,
    customKey: false,
    cashOnDeliveryCommission: 0,
    cashOnDeliveryAmount: 0,
    calculatedDeclaredValue: 0,
    isMps: false,
    shipmentTaxes: [],
    branches: [],
    costSummary: [
      {
        quantity: 1,
        basePrice: 169.83,
        basePriceTaxes: 27.17,
        extendedFare: 0,
        insurance: 0,
        additionalServices: 0,
        additionalServicesTaxes: 0,
        additionalCharges: 0,
        additionalChargesTaxes: 0,
        taxes: 27.17,
        totalPrice: 197,
        costAdditionalServices: [],
        costAdditionalCharges: [],
        currency: 'MXN',
        customKey: false,
        cashOnDeliveryCommission: 0,
        cashOnDeliveryAmount: 0,
        customKeyCommission: 0,
        smsCommission: 0,
        securityDeposit: false,
        securityWeight: 1,
        importFee: 0,
        whatsappCommission: 0,
        folio: null,
        calculatedDeclaredValue: 0,
      },
    ],
    packageDetails: {
      totalWeight: 1,
      weightUnit: 'KG',
      details: [
        {
          appliedWeightType: 'flatRate',
          weightUnit: 'KG',
          weight: 1,
          content: 'Caja .1KG - 10 x 10 x 10 cm',
        },
      ],
    },
  },
]

export const UPS = [
  {
    carrierId: 9,
    carrier: 'ups',
    carrierDescription: 'UPS',
    serviceId: 13,
    service: 'saver',
    serviceDescription: 'Ups Saver',
    dropOff: 0,
    branchType: null,
    zone: null,
    deliveryEstimate: 'Día siguiente',
    deliveryDate: {
      date: '2025-08-14',
      dateDifference: 6,
      timeUnit: 'days',
      time: '23:30',
    },
    quantity: 1,
    basePrice: 264.09,
    basePriceTaxes: 42.26,
    extendedFare: 0,
    insurance: 0,
    additionalServices: 0,
    additionalServicesTaxes: 0,
    additionalCharges: 0,
    additionalChargesTaxes: 0,
    importFee: 0,
    customKeyCost: 0,
    taxes: 42.26,
    totalPrice: 306.35,
    currency: 'MXN',
    smsCost: 0,
    whatsappCost: 0,
    customKey: false,
    cashOnDeliveryCommission: 0,
    cashOnDeliveryAmount: 0,
    calculatedDeclaredValue: 0,
    isMps: false,
    shipmentTaxes: [],
    branches: [],
    costSummary: [
      {
        quantity: 1,
        basePrice: 264.09,
        basePriceTaxes: 42.26,
        extendedFare: 0,
        insurance: 0,
        additionalServices: 0,
        additionalServicesTaxes: 0,
        additionalCharges: 0,
        additionalChargesTaxes: 0,
        taxes: 42.26,
        totalPrice: 306.35,
        costAdditionalServices: [],
        costAdditionalCharges: [],
        currency: 'MXN',
        customKey: false,
        cashOnDeliveryCommission: 0,
        cashOnDeliveryAmount: 0,
        customKeyCommission: 0,
        smsCommission: 0,
        securityDeposit: false,
        securityWeight: 1,
        importFee: 0,
        whatsappCommission: 0,
        folio: null,
        calculatedDeclaredValue: 0,
      },
    ],
    packageDetails: {
      totalWeight: 1,
      weightUnit: 'KG',
      details: [
        {
          appliedWeightType: 'flatRate',
          weightUnit: 'KG',
          weight: 1,
          content: 'Caja .1KG - 10 x 10 x 10 cm',
        },
      ],
    },
  },
]
